import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from "../components/Navbar/Navbar";  
import "bootstrap/dist/css/bootstrap.min.css";
import { ShoppingCartProvider } from '@/components/context/ShoppingCartContext'; 

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}> 
        <ShoppingCartProvider>
          <Navbar />
          {children}
        </ShoppingCartProvider>
        
      </body> 
    </html>
  )
}
